before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
  -
    name: magnetis-crawler

    github:
      owner: alfredosegundo
      name: homebrew-magnetis_crawler

    url_template: "https://github.com/alfredosegundo/magnetis-crawler/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    commit_author:
      name: Alfredo Segundo
      email: alfredocavalcanti@gmail.com

    folder: Formula

    description: "Crawler of the json api of magnetis.com.br website"

    test: |
      system "#{bin}/magnetis-crawler --version"

    install: |
      bin.install "magnetis-crawler"