language: go

go:
  - 1.13

after_success:
 - go build -o magnetis-crawler main.go
 - ./magnetis-crawler curve -s
 - ./magnetis-crawler applications -s
 - ./magnetis-crawler stocks -s

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux